s=set()
print(s)
print(type(s))
l=[1,2,3,4]
# print(type(l))
s_from_list=set(l)
print(s_from_list)
s.add(1)
s.add(1)
s.add(2)
s.add(3)
s.remove(3)
# s1=s.union({1,2,3})
s1=s.intersection({1})
print(s)
print(s1)
print(len(s))
print(min(s))
print(max(s))
s2=set({1,2,3,4,5}) # or s2={1,2,3,4,5} is same
print(s2)
print(s.isdisjoint(s2))
