mystr="Saurav is a good boy"
print(len(mystr))
# print(mystr[0:9:2])
# print(mystr[::])
# print(mystr[:])
# print(mystr[::2])
# print(mystr[::-1])
# print(mystr[::-2])
# print(mystr[-1:0])
# print(mystr[-2:-1])
print(mystr.isalnum())
print(mystr.isalpha())
print(mystr.endswith("boy"))
print(mystr.count("o"))
print(mystr.capitalize())
print(mystr.find("is"))
print(mystr.lower())
print(mystr.upper())
print(mystr.replace("is","is not"))